exports_files([
    "AndroidManifest.xml.tpl",
    "AndroidRunner.sh.tpl",
    "MainActivity.kt.tpl",
    "app-build.gradle.kts.tpl",
    "gradle.properties.tpl",
    "proguard-rules.pro.tpl",
    "root-build.gradle.kts.tpl",
    "settings.gradle.kts.tpl",
], visibility = ["//visibility:public"])
