module(
    name = "sgl.bzl"

    #version = ""
    #compatibility_level = 0
)

bazel_dep(name = "rules_scala", version = "7.1.1")
bazel_dep(name = "rules_jvm_external", version = "6.8")
bazel_dep(name = "rules_go", version = "0.50.1")
bazel_dep(name = "platforms", version = "1.0.0")

# Register a prebuild protoc toolchain to avoid always re-compiling protoc.
# require the flag --incompatible_enable_proto_toolchain_resolution
scala_protoc = use_extension(
    "@rules_scala//scala/extensions:protoc.bzl",
    "scala_protoc",
    dev_dependency = True,
)
use_repo(scala_protoc, "rules_scala_protoc_toolchains")
register_toolchains(
    "@rules_scala_protoc_toolchains//...:all",
    dev_dependency = True,
)

scala_config = use_extension(
    "@rules_scala//scala/extensions:config.bzl",
    "scala_config",
)
scala_config.settings(scala_version = "2.13.16")

scala_deps = use_extension(
    "@rules_scala//scala/extensions:deps.bzl",
    "scala_deps",
)
# Defines a default toolchain repo for the configured Scala version that loads
# Maven deps like the Scala compiler and standard libs. Enable and configure
# other builtin toolchains by instantiating their corresponding tag classes.
# See the documentation in `scala/extensions/deps.bzl` for all builtin
# toolchain configuration options.
#
# On production projects, you may consider defining a custom toolchain to use
# your project's required dependencies instead. In that case, you can omit using
# the module extension and this next line altogether. Or, you can still use the
# module extension to instantiate other optional `rules_scala` toolchains
# without it.
scala_deps.scala()
#scala_deps.scalafmt()
scala_deps.scalatest()

maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
    artifacts = [
        "com.googlecode.soundlibs:vorbisspi:1.0.3-2",
        "net.liftweb:lift-json_2.13:3.4.3", 
        "org.scalatest:scalatest_2.13:3.2.19",
        "org.scala-js:scalajs-compiler_2.13.16:1.19.0",
        "org.scala-js:scalajs-library_2.13:1.19.0",
        "org.scala-js:scalajs-linker_2.13:1.19.0",
        "org.scala-js:scalajs-linker-interface_2.13:1.19.0",
        "org.scala-js:scalajs-ir_2.13:1.19.0",
        "org.scala-js:scalajs-dom_sjs1_2.13:2.8.1",
    ],
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
    lock_file = "//third_party:maven_install.json",
)
use_repo(maven, "maven")

#register_toolchains("//:my_toolchain")
