module(
    name = "sgl.bzl"

    #version = ""
    #compatibility_level = 0
)

bazel_dep(name = "rules_scala", version = "7.2.6")
bazel_dep(name = "rules_jvm_external", version = "7.0")
bazel_dep(name = "rules_go", version = "0.61.1")
bazel_dep(name = "rules_java", version = "9.6.1")
bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "protobuf", version = "33.4")

scala_config = use_extension(
    "@rules_scala//scala/extensions:config.bzl",
    "scala_config",
)
scala_config.settings(scala_version = "3.3.8")

scala_deps = use_extension(
    "@rules_scala//scala/extensions:deps.bzl",
    "scala_deps",
)
# Defines a default toolchain repo for the configured Scala version that loads
# Maven deps like the Scala compiler and standard libs. Enable and configure
# other builtin toolchains by instantiating their corresponding tag classes.
# See the documentation in `scala/extensions/deps.bzl` for all builtin
# toolchain configuration options.
#
# On production projects, you may consider defining a custom toolchain to use
# your project's required dependencies instead. In that case, you can omit using
# the module extension and this next line altogether. Or, you can still use the
# module extension to instantiate other optional `rules_scala` toolchains
# without it.
scala_deps.scala()
#scala_deps.scalafmt()
scala_deps.scalatest()

maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
    known_contributing_modules = ["protobuf"],
    artifacts = [
        "com.googlecode.soundlibs:vorbisspi:1.0.3-2",
        "net.liftweb:lift-json_2.13:3.4.3", 
        "org.scalatest:scalatest_3:3.2.19",
        "org.scala-js:scalajs-compiler_2.13.18:1.20.1",
        "org.scala-js:scalajs-library_2.13:1.20.1",
        "org.scala-js:scalajs-linker_2.13:1.20.1",
        "org.scala-js:scalajs-linker-interface_2.13:1.20.1",
        "org.scala-js:scalajs-ir_2.13:1.20.1",
        "org.scala-js:scalajs-dom_sjs1_3:2.8.1",
        "org.scala-native:nscplugin_3.3.8:0.5.12",
        "org.scala-native:scalalib_native0.5_3:3.3.8+0.5.12",
        "org.scala-native:scala3lib_native0.5_3:3.3.8+0.5.12",
        "org.scala-native:nativelib_native0.5_3:0.5.12",
        "org.scala-native:clib_native0.5_3:0.5.12",
        "org.scala-native:posixlib_native0.5_3:0.5.12",
        "org.scala-native:javalib_native0.5_3:0.5.12",
        "org.scala-native:auxlib_native0.5_3:0.5.12",
        "org.scala-native:tools_3:0.5.12",
        "org.scala-native:util_3:0.5.12",
        "org.lwjgl:lwjgl:3.3.6",
        "org.lwjgl:lwjgl-glfw:3.3.6",
        "org.lwjgl:lwjgl-opengl:3.3.6",
        "org.lwjgl:lwjgl-openal:3.3.6",
        "org.lwjgl:lwjgl-stb:3.3.6",
        "org.lwjgl:lwjgl::natives-linux:3.3.6",
        "org.lwjgl:lwjgl-glfw::natives-linux:3.3.6",
        "org.lwjgl:lwjgl-opengl::natives-linux:3.3.6",
        "org.lwjgl:lwjgl-openal::natives-linux:3.3.6",
        "org.lwjgl:lwjgl-stb::natives-linux:3.3.6",
        "org.lwjgl:lwjgl::natives-linux-arm64:3.3.6",
        "org.lwjgl:lwjgl-glfw::natives-linux-arm64:3.3.6",
        "org.lwjgl:lwjgl-opengl::natives-linux-arm64:3.3.6",
        "org.lwjgl:lwjgl-openal::natives-linux-arm64:3.3.6",
        "org.lwjgl:lwjgl-stb::natives-linux-arm64:3.3.6",
        "org.lwjgl:lwjgl::natives-windows:3.3.6",
        "org.lwjgl:lwjgl-glfw::natives-windows:3.3.6",
        "org.lwjgl:lwjgl-opengl::natives-windows:3.3.6",
        "org.lwjgl:lwjgl-openal::natives-windows:3.3.6",
        "org.lwjgl:lwjgl-stb::natives-windows:3.3.6",
        "org.lwjgl:lwjgl::natives-macos:3.3.6",
        "org.lwjgl:lwjgl-glfw::natives-macos:3.3.6",
        "org.lwjgl:lwjgl-opengl::natives-macos:3.3.6",
        "org.lwjgl:lwjgl-openal::natives-macos:3.3.6",
        "org.lwjgl:lwjgl-stb::natives-macos:3.3.6",
        "org.lwjgl:lwjgl::natives-macos-arm64:3.3.6",
        "org.lwjgl:lwjgl-glfw::natives-macos-arm64:3.3.6",
        "org.lwjgl:lwjgl-opengl::natives-macos-arm64:3.3.6",
        "org.lwjgl:lwjgl-openal::natives-macos-arm64:3.3.6",
        "org.lwjgl:lwjgl-stb::natives-macos-arm64:3.3.6",
    ],
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
)
use_repo(maven, "maven")

#register_toolchains("//:my_toolchain")

# Tiled tool extension
tiled = use_extension("//bazel/tiled:extensions.bzl", "tiled_extension")
use_repo(tiled, "tiled_tool")
