
exports_files([
    "Html5Main.scala.template",
    "Html5OpenGLMain.scala.template",
    "DesktopAWTMain.scala.template",
    "DesktopLwjglMain.scala.template",
    "DesktopNativeMain.scala.template",
], visibility=["//visibility:private"])

