name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Scala Native dependencies
      run: sudo apt-get install clang libunwind-dev libgc-dev libre2-dev libglu1-mesa-dev
    - name: Run tests
      run: sbt verifyCI
